// src/lib/constants.ts

export const RISK_CATEGORIES = {
  critical: { label: 'Critical', min: 80, max: 100 },
  high: { label: 'High', min: 60, max: 79 },
  moderate: { label: 'Moderate', min: 40, max: 59 },
  low: { label: 'Low', min: 20, max: 39 },
  minimal: { label: 'Minimal', min: 0, max: 19 },
} as const;

export const DIFFICULTY_LABELS = {
  trivial: '~5 min',
  easy: '~15 min',
  moderate: '~30 min',
  challenging: '~60 min',
  complex: '~2+ hours',
} as const;

export const ACTION_CATEGORIES = {
  billing: { label: 'Bill Dispute', icon: 'FileText' },
  insurance: { label: 'Insurance', icon: 'Shield' },
  assistance: { label: 'Financial Aid', icon: 'Heart' },
  negotiation: { label: 'Negotiation', icon: 'MessageSquare' },
  payment: { label: 'Payment', icon: 'CreditCard' },
  optimization: { label: 'Optimization', icon: 'TrendingUp' },
} as const;

export const US_STATES = [
  { value: 'AL', label: 'Alabama' },
  { value: 'AK', label: 'Alaska' },
  { value: 'AZ', label: 'Arizona' },
  { value: 'AR', label: 'Arkansas' },
  { value: 'CA', label: 'California' },
  { value: 'CO', label: 'Colorado' },
  { value: 'CT', label: 'Connecticut' },
  { value: 'DE', label: 'Delaware' },
  { value: 'FL', label: 'Florida' },
  { value: 'GA', label: 'Georgia' },
  { value: 'HI', label: 'Hawaii' },
  { value: 'ID', label: 'Idaho' },
  { value: 'IL', label: 'Illinois' },
  { value: 'IN', label: 'Indiana' },
  { value: 'IA', label: 'Iowa' },
  { value: 'KS', label: 'Kansas' },
  { value: 'KY', label: 'Kentucky' },
  { value: 'LA', label: 'Louisiana' },
  { value: 'ME', label: 'Maine' },
  { value: 'MD', label: 'Maryland' },
  { value: 'MA', label: 'Massachusetts' },
  { value: 'MI', label: 'Michigan' },
  { value: 'MN', label: 'Minnesota' },
  { value: 'MS', label: 'Mississippi' },
  { value: 'MO', label: 'Missouri' },
  { value: 'MT', label: 'Montana' },
  { value: 'NE', label: 'Nebraska' },
  { value: 'NV', label: 'Nevada' },
  { value: 'NH', label: 'New Hampshire' },
  { value: 'NJ', label: 'New Jersey' },
  { value: 'NM', label: 'New Mexico' },
  { value: 'NY', label: 'New York' },
  { value: 'NC', label: 'North Carolina' },
  { value: 'ND', label: 'North Dakota' },
  { value: 'OH', label: 'Ohio' },
  { value: 'OK', label: 'Oklahoma' },
  { value: 'OR', label: 'Oregon' },
  { value: 'PA', label: 'Pennsylvania' },
  { value: 'RI', label: 'Rhode Island' },
  { value: 'SC', label: 'South Carolina' },
  { value: 'SD', label: 'South Dakota' },
  { value: 'TN', label: 'Tennessee' },
  { value: 'TX', label: 'Texas' },
  { value: 'UT', label: 'Utah' },
  { value: 'VT', label: 'Vermont' },
  { value: 'VA', label: 'Virginia' },
  { value: 'WA', label: 'Washington' },
  { value: 'WV', label: 'West Virginia' },
  { value: 'WI', label: 'Wisconsin' },
  { value: 'WY', label: 'Wyoming' },
] as const;

export const INSURANCE_TYPES = [
  { value: 'employer', label: 'Employer-Sponsored' },
  { value: 'marketplace', label: 'ACA Marketplace' },
  { value: 'medicare', label: 'Medicare' },
  { value: 'medicaid', label: 'Medicaid' },
  { value: 'tricare', label: 'TRICARE' },
  { value: 'private', label: 'Private/Individual' },
  { value: 'none', label: 'Uninsured' },
] as const;